version: "3"
services:
  bulder-db:
    hostname: bulder-db
    image: lscr.io/linuxserver/mariadb:latest
    container_name: bulder-db
    networks:
      - backend
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      - MYSQL_ROOT_PASSWORD=asijsadijodaijodsai
      - MYSQL_DATABASE=bulder
      - MYSQL_USER=budlderuser
      - MYSQL_PASSWORD=fdopakakpofsap    
      - MARIADB_ROOT_PASSWORD=asijsadijodaijodsai
      - MARIADB_DATABASE=bulder
      - MARIADB_USER=budlderuser
      - MARIADB_PASSWORD=fdopakakpofsap
    ports:
      - 3306:3306
    volumes:
      - bulder-db:/var/lib/mysql
  bulder-dbbackuper:
    hostname: bulder-dbbackuper
    build:
      context: .
      dockerfile: dbbackuper/Dockerfile
    container_name: bulder-dbbackuper
    networks:
      - backend
    depends_on:
      - bulder-db
    volumes:
      - ./dbbackuper/bin/crontab:/var/spool/cron/crontabs/root
      - ./dbbackuper/bin/backup:/usr/local/bin/backup
      - ./backup:/backup
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: bulder-db
      MYSQL_USER: root
      MYSQL_PASSWORD: asijsadijodaijodsai
      MYSQL_DATABASE: bulder
  bulder-web:
    hostname: bulder-web
    build:
      context: .
      dockerfile: webserver/Dockerfile
    container_name: bulder-web
    networks:
      - backend
      - frontend
    depends_on:
      - bulder-db
    volumes:
      - ./web/:/var/www/html
    ports:
      - 7000:80


networks:
  backend:
  frontend:

volumes:
  bulder-db: