version: "3"
services:
  bulder-db:
    hostname: bulder-db
    image: mariadb:latest
    container_name: bulder-db
    networks:
      - backend
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_520_ci
    environment:
      - MYSQL_ROOT_PASSWORD=asijsadijodaijodsai
      - MYSQL_DATABASE=bulder
      - MYSQL_USER=budlderuser
      - MYSQL_PASSWORD=fdopakakpofsap    
      - MARIADB_ROOT_PASSWORD=asijsadijodaijodsai
      - MARIADB_DATABASE=bulder
      - MARIADB_USER=budlderuser
      - MARIADB_PASSWORD=fdopakakpofsap
    ports:
      - 3306:3306
    volumes:
      - bulder-db:/var/lib/mysql
  bulder-web:
    hostname: bulder-web
    build:
      context: .
      dockerfile: webserver/Dockerfile
    container_name: bulder-web
    networks:
      - backend
      - frontend
    depends_on:
      - bulder-db
    volumes:
      - ./web/:/var/www/html
    ports:
      - 7000:80

networks:
  backend:
  frontend:

volumes:
  bulder-db: